### ISSUE TITLE
Add support for ingestion job to write to Snowflake target

### ISSUE THREAD

**Issue by rhasson** [Upsolver/dbt-upsolver#10]
Support writing the output of an ingestion job to Snowflake (in addition to the data lake).

I propose adding a new `TARGET_TYPE` and `TARGET_CONNECTION` properties in the config block. If the property is not included the model will default to a target of `DATALAKE`. 

The following targets will be supported:

`target_type = 'SNOWFLAKE',
 target_connection = 'some_conn_name'`

`target_type = 'DATALAKE', 
target_connection = 'default_glue_catalog'`

Also support the following new required job properties for `SNOWFLAKE` targets **only**:

```
COLUMN_TRANSFORMATIONS = (<column> = <expression>, ...)
DEDUPLICATE_WITH = ( {COLUMNS = (<col>, ...)  | COLUMN = <col>}, WINDOW = INT <time unit>)
EXCLUDE_COLUMNS = ({<column_name> | <glob_pattern>}, ...)
CREATE_TABLE_IF_MISSING = True | False
WRITE_INTERVAL = INT <time unit>
```

Example: ingest_to_sf.sql
```
{{ config(  
            materialized='incremental',
            sync = True,
            source = 'KAFKA',
            target_type = 'SNOWFLAKE',
            target_connection = 'sf_conn_name',
            schema = 'ROYON'.  -- dbt override
            options = { 
               'topic' = 'user_info',
               'EXCLUDE_COLUMNS': ['password', 'username'],
               'DEDUPLICATE_WITH': { 
                    'COLUMNS' : ['first_name'], 
                    'WINDOW': '1 HOURS'
                },
               'COLUMN_TRANSFORMATIONS' = { 'credit_card': 'MD5(credit_card)' } ,
               'WRITE_INTERVAL': '1 MINUTES',
               'CREATE_TABLE_IF_MISSING': True,
               'COMPUTE_CLUSTER': 'SQLake',
               'START_FROM': 'NOW'
            },
            partition_by=[{...}],
            primary_key=[{...}]
        )
}}

SELECT * FROM {{ ref('source_kafka_conn') }}
```
This `ingest_to_sf.sql` model will compile to the following SQL.

```
CREATE SYNC JOB "ingest_to_sf"
    COMPUTE_CLUSTER = SQLake
    CREATE_TABLE_IF_MISSING = true
    START_FROM = NOW
    EXCLUDE_COLUMNS = ('password', 'username')
    DEDUPLICATE_WITH = (COLUMNS = (first_name) WINDOW = 1 HOURS)
    COLUMN_TRANSFORMATIONS = (credit_card = MD5(credit_card))
    WRITE_INTERVAL = 1 MINUTES
AS COPY FROM KAFKA source_kafka_conn TOPIC = 'user_info'
INTO SNOWFLAKE sf_conn_name.ROYON.INGEST_TO_SF;
```
Implementations notes:
- `SNOWFLAKE` keyword is added to the `INTO` statement when target is of type `SNOWFLAKE`
- A `DATALAKE` keyword is **NOT** added to the `INTO` statement when the target type is `DATALAKE`
- The `TARGET_CONNECTION` property value is inserted before the schema name in the `INTO` statement
- If `CREATE_TABLE_IF_MISSING = True` Upsolver will automatically create the target table in Snowflake, which the job will load data into.  If `CREATE_TABLE_IF_MISSING = False` the table is expected to already be present in the target Snowflake system. If not the job will fail to load data. 
- The target database name and schema name can be configured in the `dbt_project.yml` or via the config properties `database` and `schema`. Docs for [schema](https://docs.getdbt.com/reference/resource-configs/schema) and [database](https://docs.getdbt.com/reference/resource-configs/database). It may be useful to override these if you want to output to multiple targets.

Updated to reflect @jasonf20 feedback

**Comment by jasonf20** [comment]
Seems fine, I think we should  split the target option into two options:
```
TARGET_TYPE
TARGET_CONNECTION
```

As we should already have the CONNECTION property from before since when loading to Upsolver you should have been able to configure that. That way you don't have to configure the `TYPE` if you just want to change the connection. 

Also, IMO, I think our target should be called `Upsolver` not `Datalake`. Alternatively, it can be called `Glue` but that has the feeling that it's a native glue table that we don't manage beyond the `DBT RUN`. `Datalake` seems like an abstract thing and not a concrete target. It might be fine since it's within the context of the Upsolver connector, but seems odd still.


Another point to consider:
Do you want to have full `COLUMN_TRANSFORMATIONS` or just a `HASH` list? The first is more powerful of course, but we elected to only expose the simpler HASH list in our wizards.

**Comment by rhasson** [comment]
I agree with connection options and will update.

Regarding the output table of data lake, I'm hesitant to call it Upsolver because it feels proprietary when in fact we create a standard data lake table, although with a MOR view.  Datalake is commonly used to represent queryable objects in S3 so I think the name conveys the purpose. It doesn't however convey the fact that we manage it.  What about `DATALAKE_MOR` ?

Regarding `COLUMN_TRANSFORMATIONS` I think we should keep this and not use only `HASH`, because we will add more functions in the future so we should have foundation ready.

**Comment by jasonf20** [comment]
Well, I guess it goes back to the discussion if the GLUE catalog in Upsolver is supposed to be called glue or something like Upsolver Catalog. I think Datalake is abstract while SNOWFLAKE is concrete so they don't really match, but I don't have a strong opinion on this one.
