### ISSUE TITLE
"primary_key" property should be "unique_key"

### ISSUE THREAD

**Issue by rhasson** [Upsolver/dbt-upsolver#6]
The "primary_key" property should be renamed to "unique_key" per the revised requirements.

**Comment by tanyshak** [comment]
The "unique_key" is already used  in the dbt config
https://docs.getdbt.com/reference/resource-configs/unique_key

**Comment by rhasson** [comment]
When I try to set unique_key, it doesn't create the target table with the key.

```
royhasson@roys-mbp-2 models % cat royon_merge_w_delete.sql
{{ config(  materialized='incremental',
            incremental_strategy='merge',
            map_columns_by_name=True,
            sync=True,
            options={
              'START_FROM': 'NOW',
              'ADD_MISSING_COLUMNS': True,
              'RUN_INTERVAL': '1 MINUTE',
              'COMPUTE_CLUSTER': 'SQLake'
            },
            unique_key='user_id',
            partition_by=[{'field':'$event_date', 'type':'date'}]
          )
}}

```
Here is the output from dbt run command:

```
12:16:16  On model.dbt_demo.royon_merge_w_delete: /* {"app": "dbt", "dbt_version": "1.5.0", "profile_name": "dbt_demo", "target_name": "dev", "node_id": "model.dbt_demo.royon_merge_w_delete"} */

  

  
    CREATE TABLE "default_glue_catalog"."royon"."royon_merge_w_delete"
    ($event_date date)
    
      PARTITIONED BY
      $event_date
    
    
    
      
         COMPUTE_CLUSTER = "SQLake"
      
  
12:16:16  Opening a new connection, currently in state closed
```

From the Upsolver console I can see the table was not created with a primary key.

![image](https://user-images.githubusercontent.com/1313604/236822533-5f6c7bed-1deb-4963-9fb1-554849d8e8aa.png)

**Comment by tanyshak** [comment]
Sorry, my previous message was ambiguous.
We use primary key=[{'field':'order_id', 'type':'string'}] 
Because "unique_key" is already used in the dbt config. It's a registered word for snapshots. https://docs.getdbt.com/reference/resource-configs/unique_key
